Repository MicrosoftDocs/visualstudio-docs.zh-tw, pull requests merged in 2018-10, with the labels that each got.

#22 Typo: crsf → csrf
  docs/python/learn-django-in-visual-studio-step-05-django-authentication.md
Labels: Accepted, Source Issue

#30 Update managing-exceptions-with-the-debugger.md
  docs/debugger/managing-exceptions-with-the-debugger.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#29 Update just-in-time-debugging-in-visual-studio.md
  docs/debugger/just-in-time-debugging-in-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#28 Update walkthrough-debugging-at-design-time.md
  docs/debugger/walkthrough-debugging-at-design-time.md
Labels: Accepted, Linguistic Suggestion

#27 Update debug-using-the-just-in-time-debugger.md
  docs/debugger/debug-using-the-just-in-time-debugger.md
Labels: Accepted, Linguistic Suggestion

#26 Update attach-to-running-processes-with-the-visual-studio-debugger.md
  docs/debugger/attach-to-running-processes-with-the-visual-studio-debugger.md
Labels: Accepted, Linguistic Suggestion

#25 quickstart-deploy-to-azure.md suggestion
  docs/deployment/quickstart-deploy-to-azure.md
Labels: Accepted, Linguistic Suggestion

#33 deploying-applications-services-and-components.md suggestion
  docs/deployment/deploying-applications-services-and-components.md
Labels: Accepted, Linguistic Suggestion
