Repository MicrosoftDocs/visualstudio-docs.zh-tw, pull requests merged in 2019-04, with the labels that each got.

#65 Update convert-foreach-linq.md
  docs/ide/reference/convert-foreach-linq.md
Labels: Accepted, Linguistic Suggestion

#63 Update convert-anonymous-type-to-class.md
  docs/ide/reference/convert-anonymous-type-to-class.md
Labels: Accepted, Linguistic Suggestion

#64 Update convert-for-loop-to-foreach.md
  docs/ide/reference/convert-for-loop-to-foreach.md
Labels: Linguistic Suggestion, Partially Accepted

#69 Fixed error wording.
  docs/ide/quickstart-aspnet-core.md
Labels: Accepted, Linguistic Suggestion

#70 Delete superfluous symbols
  docs/debugger/just-my-code.md
Labels: In Progress
